---
apiVersion: gcp.project-planton.org/v1
kind: GcpSubnetwork
metadata:
  name: ${values.env}-${values.subnet_name}
spec:
  project_id:
    value: ${values.project_id}
  vpc_self_link:
    valueFrom:
      kind: GcpVpc
      name: ${values.env}-${values.vpc_name}
      fieldPath: status.outputs.network_self_link
  region: ${values.region}
  ip_cidr_range: ${values.subnet_primary_cidr}
  secondary_ip_ranges:
    - range_name: ${values.pods_secondary_range_name}
      ip_cidr_range: ${values.pods_secondary_cidr}
    - range_name: ${values.services_secondary_range_name}
      ip_cidr_range: ${values.services_secondary_cidr}
  private_ip_google_access: ${values.private_ip_google_access}
