---
apiVersion: gcp.project-planton.org/v1
kind: GcpVpc
metadata:
  name: ${values.env}-${values.vpc_name}
spec:
  project_id:
    valueFrom:
      kind: GcpProject
      name: ${values.project_id}
      fieldPath: status.outputs.project_id
  auto_create_subnetworks: ${values.vpc_auto_create_subnetworks}
  routing_mode: REGIONAL
