---
apiVersion: digital-ocean.project-planton.org/v1
kind: DigitalOceanKubernetesNodePool
metadata:
  name: "{{ values.node_pool_name }}"
spec:
  nodePoolName: "{{ values.node_pool_name }}"
  cluster:
    valueFrom:
      kind: DigitalOceanKubernetesCluster
      name: "{{ values.cluster_name }}"
      fieldPath: metadata.name
  sizeSlug: "{{ values.node_size_slug }}"
  nodeCount: {{ values.node_count }}
  autoScale: {{ values.node_auto_scale }}
  {% if values.node_auto_scale | bool %}
  minNodes: {{ values.node_min_nodes }}
  maxNodes: {{ values.node_max_nodes }}
  {% endif %}
  tags:
    - "{{ values.env }}"
    - "{{ values.node_pool_name }}"
