---
apiVersion: kubernetes.project-planton.org/v1
kind: CertManagerKubernetes
metadata:
  name: cert-manager
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: ${values.cluster_name}
---
apiVersion: kubernetes.project-planton.org/v1
kind: ElasticOperatorKubernetes
metadata:
  name: elastic-operator
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: ${values.cluster_name}
---
apiVersion: kubernetes.project-planton.org/v1
kind: ExternalDnsKubernetes
metadata:
  name: external-dns
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: ${values.cluster_name}
---
apiVersion: kubernetes.project-planton.org/v1
kind: ExternalSecretsKubernetes
metadata:
  name: external-secrets
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: ${values.cluster_name}
---
apiVersion: kubernetes.project-planton.org/v1
kind: IngressNginxKubernetes
metadata:
  name: ingress-nginx
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: ${values.cluster_name}
---
apiVersion: kubernetes.project-planton.org/v1
kind: IstioKubernetes
metadata:
  name: istio-ingress
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: ${values.cluster_name}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KafkaOperatorKubernetes
metadata:
  name: kafka-operator
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: ${values.cluster_name}
---
apiVersion: kubernetes.project-planton.org/v1
kind: PostgresOperatorKubernetes
metadata:
  name: postgres-operator
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: ${values.cluster_name}
---
apiVersion: kubernetes.project-planton.org/v1
kind: SolrOperatorKubernetes
metadata:
  name: solr-operator
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: ${values.cluster_name}

