{% if values.storageBucketEnabled | bool %}
---
apiVersion: gcp.project-planton.org/v1
kind: GcpGcsBucket
metadata:
  name: "{{ values.storage_bucket_name }}"
  {% if values.serviceAccountEnabled | bool %}
  relationships:
    - kind: GcpServiceAccount
      name: "{{ values.service_account_id }}"
      type: depends_on
      group: storage
  {% endif %}
spec:
  gcpProjectId: "{{ values.gcp_project_id }}"
  gcpRegion: "{{ values.gcp_region }}"
{% endif %}

