---
apiVersion: aws.project-planton.org/v1
kind: AwsEcsCluster
metadata:
  name: ${values.env}-ecs-cluster
  org: ${values.org}
  env: ${values.env}
spec:
  capacityProviders:
    - FARGATE
    - FARGATE_SPOT
